### ISSUE TITLE
Question Regarding the Absence of Controller Settings on Steam Deck

### ISSUE THREAD

**Issue by shyun12** [ctu-vras/steam-deck-ros-controller#3]
![no_Controller_Screenshot_20230830_](https://github.com/ctu-vras/steam-deck-ros-controller/assets/142779942/45ede6cc-9fe7-4d46-a83a-f7aa6d436b3d)

Hi, 
I'm currently following the Steam Deck ROS installation guide provided by you. You mentioned to go to "Settings -> Controller -> Desktop configuration." However, as shown in the screenshot above, we cannot find the controller option in the settings menu on our Steam Deck. We would like to ask where we should perform the settings.

Thank you for providing this guide.

**Comment by peci1** [comment]
You're missing the very first part: `Tap the Steam icon in taskbar`. It's not the system settings you should open, it's Steam settings.
